### ISSUE TITLE
Images attached on desktop get distorted, won't show on mobile [Windows, Android]

### ISSUE THREAD

**Issue by luxcalor** [streetwriters/notesnook#3009]
### What happened?

When attaching the image in the desktop app (2.5.8-9e3646e) it gets distorted or shown only in half after the sync/app restart. Also the newly attached images are not displayed in the android app (2.5.6), only a placeholder is visible. 

Images attached in previous desktop versions are intact on both platforms. 

### Steps to reproduce the problem

See above

### Version

2.5.8-9e3646e-desktop, 2.5.6-mobile

### Platform/OS

Windows, Android

**Comment by thecodrr** [comment]
This was already fixed in v2.5.8. What's happening is that you are attaching images/files that were already uploaded once and got corrupted. If you delete those attachments from the attachments manager and reupload them, it'll work.

**Comment by luxcalor** [comment]
I deleted all the attachments from the note's attachment manager on windows and restarted the app, then reattached the images to the same note. Did this several times.
1. Only one of the images showed up in the mobile app. Other 5 appear as placeholders still. Previously not used images do not appear on mobile either.
2. After deleting the image from attachment manager the note gets force closed and the blank note appears instead. After this no cursor is visible in any note and editing is problematic, only app restart helps. 
3. Sync failed message is showing in the desktop app and no changes happen immediately on mobile too. Force sync is required on both platforms to see the images on mobile (or placeholders, for that matter). Also android app restart is required.

**Comment by luxcalor** [comment]
UPD: I created a new note, copied the text, deleted the images in an old note and reattached them to the new one on desktop and they showed on mobile. 

Other 2 issues are still there: sync fail message and cursor disappearance after image deletion.

**Comment by luxcalor** [comment]
All the issues mentioned are fixed.
