### ISSUE TITLE
Newlines are lost when importing from Standard Notes

### ISSUE THREAD

**Issue by bocekm** [streetwriters/notesnook#3174]
### What happened?

A single newline is replaced with just a space when importing the zip file with notes from Standard Notes.

Two newlines are replaced with a single newline.

I cannot start using the notesnook with having my notes butchered like that.

Standard Notes:
![Screenshot from 2023-08-17 13-48-10](https://github.com/streetwriters/notesnook/assets/9884110/6198ef74-0360-4456-b190-7b15f586eb31)

Notesnook:
![Screenshot from 2023-08-17 13-48-42](https://github.com/streetwriters/notesnook/assets/9884110/eb265bc8-bfd1-407b-be74-05471669050b)

### Steps to reproduce the problem

https://help.notesnook.com/importing-notes/import-notes-from-standardnotes

In Standard Notes I'm not using any formatting, just plain text.

### Version

2.6.1-e509c82-web

### Platform/OS

Chrome/Chromium

**Comment by thecodrr** [comment]
@bocekm is that plain text or markdown? I know you said it's just plain text but it actually makes a very significant difference if you are using the Markdown Editor in SN.

**Comment by bocekm** [comment]
No markdown as I'm using the free version of SN that does not allow anything besides plaintext.

**Comment by thecodrr** [comment]
@bocekm can you send a sample backup file to reproduce the issue?

**Comment by bocekm** [comment]
[Standard Notes Backup and Import File.txt](https://github.com/streetwriters/notesnook/files/13252953/Standard.Notes.Backup.and.Import.File.txt)

**Comment by thecodrr** [comment]
@bocekm thank you!

**Comment by thecodrr** [comment]
@bocekm this has been fixed in v2.1.0 of the Importer.

**Comment by bocekm** [comment]
@thecodrr, this hasn't been fixed. I've just tried the import today and the newlines are still missing in the imported notes.
