### ISSUE TITLE
If click anywhere on a line with a link, the link will open in the browser

### ISSUE THREAD

**Issue by foozzi** [streetwriters/notesnook#3315]
### What happened?

If click anywhere on a line with a link, the link will open in the browser

https://github.com/streetwriters/notesnook/assets/1178208/8920459f-c7cf-486b-9bcb-f60e0672032d

### Steps to reproduce the problem

1. place a link in your note
2. click anywhere on a line with the link 

### Version

2.6.2

### Platform/OS

macOS

**Comment by thecodrr** [comment]
Yes, this is a bug in TipTap. It was fixed recently, though, so you'll probably not experience it in the next release.

**Comment by ckdanny** [comment]
It was tested in the 2.6.4, the problem improved but still exists.
![2023-09-14 18 07 56](https://github.com/streetwriters/notesnook/assets/11786201/23847665-438f-4843-934f-dbd63320b19f)

**Comment by foozzi** [comment]
Is it fixed?
