### ISSUE TITLE
Import notes duplicate files and make them hidden

### ISSUE THREAD

**Issue by dmytrodubinin** [streetwriters/notesnook#5804]
### What happened?

When I try to import my notes into Notesnook, importer create the same names of file but hidden:
<img width="789" alt="image" src="https://github.com/streetwriters/notesnook/assets/8066458/73898a13-36bc-41b1-9b9b-36ac2fa19820">
And when I import arhive this files also appear in application but with the same text:
<img width="1393" alt="image" src="https://github.com/streetwriters/notesnook/assets/8066458/97993203-06c5-443d-88ec-01936ca870fe">

The content of this hidden files:
`����Mac OS X        ����	���2���q���������������������������������������������ATTR���������������������������������������com.apple.provenance���1(����`

### Steps to reproduce the problem

Tested different md files from Obsidian and vanilla markdown, the problem is still here

### Version

3.0.6-10be577-desktop

### Platform/OS

macOS

**Comment by ammarahm-ed** [comment]
Hi, are the imported notes that are not hidden load properly in the editor. Only the hidden files have this problem?

**Comment by dmytrodubinin** [comment]
> Hi, are the imported notes that are not hidden load properly in the editor. Only the hidden files have this problem?

Yes, original files (not hidden) doesn't have this problem. But this imported files have another problem related to this issue: https://github.com/streetwriters/notesnook/issues/4245 - the problem appears not in pdf files but in images (they detected as files, not images):
<img width="1181" alt="image" src="https://github.com/streetwriters/notesnook/assets/8066458/aed15e04-a07d-4d03-9633-bcbf5b246b8b">
On desktop this files:
<img width="330" alt="image" src="https://github.com/streetwriters/notesnook/assets/8066458/872b58c7-38fa-4127-992c-6b25897b58ea">

On mobile app shows them as files, not images (in images section nothing):
![telegram-cloud-photo-size-2-5386758896611351218-y](https://github.com/streetwriters/notesnook/assets/8066458/bdbf5627-a7b2-4000-af85-fa4c6f7c78e3)
![telegram-cloud-photo-size-2-5386758896611351219-y](https://github.com/streetwriters/notesnook/assets/8066458/f35cfa0d-6f65-494f-9dfd-5447c24001ff)

**Comment by dmytrodubinin** [comment]
I got a lot of problems when trying to import files from Obsidian to Notesnook:
1. Hidden files appear, that I describe before
2. With import directly from Obsidian file doesn't imported at all! My structure of notes are: `_assets` - all files of my notes, then `folder_1`, `folder_2` etc for folders and subfolders. Then I try to import this notes - no files and images was imported at all!
3. So I convert my Obsidian files into vanilla markdown and imported them - they imported but with some other small bugs that i described before

**Comment by ammarahm-ed** [comment]
Hey, can you tap on the attachment in attachment manager and check it's mime type from properties?

**Comment by dmytrodubinin** [comment]
![telegram-cloud-photo-size-2-5386758896611351303-y](https://github.com/streetwriters/notesnook/assets/8066458/d5cd21c2-6b0c-4e19-9c92-529bac7e4243)

**Comment by dmytrodubinin** [comment]
I tested again, convert one note in Obsidian and import it into Notesnook: no hidden files but the problem with files are still here. The original note (archived by MacOs Finder): 
[output.zip](https://github.com/streetwriters/notesnook/files/15495779/output.zip)

Original note opens good in VSCode with preview.
The Notesnook also imported it but the problem with images when try to preview them (as before):
<img width="1166" alt="image" src="https://github.com/streetwriters/notesnook/assets/8066458/170bf12b-b4fb-45bf-b7e0-8744312721ca">

**Comment by dmytrodubinin** [comment]
I think the problem with hidden md files when import is not big problem because I can sort files by name and select them all and delete at once. But the problem with preview images are much bigger

**Comment by dmytrodubinin** [comment]
Any plan to fix the problem of images preview error?

**Comment by thecodrr** [comment]
The problem with hidden files was fixed.

**Comment by mburazin** [comment]
When was it fixed ? 

I still have this issue on Version 3.0.19 (240). The duplicate hidden files only appear if I add a zip archive to Notesnook Obsidian importer at https://importer.notesnook.com/ and then import the output file to Notesnook. If I copy `.md` files without zipping them to Obsidian importer, then the problem is not seen.
