### ISSUE TITLE
App won't open after Update.

### ISSUE THREAD

**Issue by laurenz0071** [streetwriters/notesnook#6411]
```
type: crash
osVersion: google/husky/husky:14/AP2A.240805.005/2024082000:user/release-keys
package: com.streetwriters.notesnook:15113
process: com.streetwriters.notesnook
processUptime: 240 + 399 ms
installer: com.android.packageinstaller

java.lang.SecurityException: com.streetwriters.notesnook: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3192)
	at android.os.Parcel.createException(Parcel.java:3176)
	at android.os.Parcel.readException(Parcel.java:3152)
	at android.os.Parcel.readException(Parcel.java:3094)
	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5875)
	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1885)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1825)
	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1813)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:757)
	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:757)
	at com.github.yamill.orientation.OrientationModule.onHostResume(Unknown Source:23)
	at com.facebook.react.bridge.ReactContext.onHostResume(Unknown Source:34)
	at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(Unknown Source:26)
	at com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState(Unknown Source:8)
	at com.facebook.react.ReactInstanceManager.lambda$setupReactContext$3(Unknown Source:0)
	at com.facebook.react.ReactInstanceManager.f(SourceFile:1)
	at com.facebook.react.r.run(SourceFile:1)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14557)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2656)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2826)
	at android.os.Binder.execTransactInternal(Binder.java:1529)
	at android.os.Binder.execTransact(Binder.java:1468)
```

**Comment by Gitfree1776** [comment]
I'm experiencing the same crash issue after downloading and opening the app from F-Droid.

**Comment by laurenz0071** [comment]
Notesnook:15113 showed the described behaviour.
The Update to Notesnook:15123 (Version 3.0.14) solved the described issue and the App is running again. I recommend an direct Installation via Obtainium from streetwriters source: https://github.com/streetwriters/notesnook

**Comment by Gitfree1776** [comment]
Fantastic, thanks a lot. It worked.

**Comment by Str4tu5** [comment]
Just updated to 3.0.16 on my Android 12 SamSung Galaxy S10 and now the app won't even openBeen using for years. Tried to install older version but package installer won't allow - says invalid. Am using the apks from here.

**Comment by ammarahm-ed** [comment]
This has been fixed v3.0.18

**Comment by Str4tu5** [comment]
Not fixed for me in 3.0.18. Still crashes every time I try to open. I can't get to my notes. Are they lost?
