### ISSUE TITLE
Tabs do not stay fixed

### ISSUE THREAD

**Issue by victor-mendes25681** [streetwriters/notesnook#7638]
### What happened?

Tabs are not staying fixed

https://github.com/user-attachments/assets/7da91962-1217-427a-a5c3-361a63205aae

### Steps to reproduce the problem

I don't know

### Version

3.0.26-2ab3218-desktop

### Platform/OS

Linux

### Relevant log output

```shell

```

**Comment by Leviob** [comment]
Duplicate of #7456. This will be fixed in an upcoming release.

**Comment by 01zulfi** [comment]
@victor-mendes25681 Thanks for opening the issue, this has been fixed.

**Comment by victor-mendes25681** [comment]
It's not fixed on mine.

I updated to the latest version

Version: 3.0.28-00250c6-desktop

**Comment by 01zulfi** [comment]
@victor-mendes25681 I'm unable to reproduce, could you create a screen recording, that would be helpful, thanks

**Comment by victor-mendes25681** [comment]
https://github.com/user-attachments/assets/4a4e59bb-96af-42e8-a0b5-0e020635b41b

In addition to the error persisting, I also identified another one. When you click on the note that is in a pinned tab, it opens another tab of its own, as I showed in the video.

I use the Appimage version of the application
