### ISSUE TITLE
What's going on with f-droid build?

### ISSUE THREAD

**Issue by neekless** [streetwriters/notesnook#8404]
The f-droid build is from February. It's almost 6 months behind. Builds are failing. What's going on?

**Comment by ammarahm-ed** [comment]
Thanks for bringing this to our attention. I am working on fixing the build now.

**Comment by RektalTk** [comment]
F-droid version 3.0.32 is working ok and I' m going back again to F-droid app. I have switched today to Google Play store latest version 3.2.10 and syncing between Android and web is not working. Vice versa is working. What I am typing on the keyboard is syncing to the Android.

**Comment by RektalTk** [comment]
I have just installed F-droid app and syncing between Android and web is working again.

**Comment by ammarahm-ed** [comment]
@RektalTk the syncing problem was in our servers that has been fixed now. 

The build on fdroid has been fixed so the latest version will be available in a few days https://gitlab.com/fdroid/fdroiddata/-/merge_requests/25491

**Comment by neekless** [comment]
> [@RektalTk](https://github.com/RektalTk) the syncing problem was in our servers that has been fixed now.
> 
> The build on fdroid has been fixed so the latest version will be available in a few days https://gitlab.com/fdroid/fdroiddata/-/merge_requests/25491

The build still failed. Please see the failure at the merge request.

**Comment by Revan335** [comment]
Other F-Droid Version Issues i can findet: https://github.com/streetwriters/notesnook/issues/6395 https://github.com/streetwriters/notesnook/issues/7265 https://github.com/streetwriters/notesnook/issues/8086

A Fix was great and can closed multiple Issues instantly!

Can you recheck the build? @ammarahm-ed 

> The build still failed. Please see the failure at the merge request.

**Comment by thecodrr** [comment]
F-Droid builds are now working again.
